services:
  - type: web
    name: concordia-backend-web
    env: docker
    dockerfilePath: Dockerfile
    healthCheckPath: /health
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
