-- Phase 1: order fulfillment fields + menu item kitchen routing
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "customerName" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "deliveryAddress" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "fulfillmentType" TEXT DEFAULT 'delivery';
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "postalCode" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "notes" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "orderTotal" DOUBLE PRECISION;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "deliveryFee" DOUBLE PRECISION DEFAULT 0;

ALTER TABLE "MenuItem" ADD COLUMN IF NOT EXISTS "kitchen" TEXT NOT NULL DEFAULT 'B';
